---
version: '3'

includes:
  angular: ./.common/taskfiles-app/Taskfile-angular.yml
  common: ./.common/taskfiles-app/Taskfile-common.yml
  fix: ./.common/taskfiles-app/Taskfile-fix.yml
  lint: ./.common/taskfiles-app/Taskfile-lint.yml
  software: ./.common/taskfiles-app/Taskfile-{{OS}}.yml
output: prefixed

vars:
  REPOSITORY_SUBTYPE: app
  REPOSITORY_TYPE: angular

