---
version: '3'

output: prefixed

vars:
  REPOSITORY_SUBTYPE: app
  REPOSITORY_TYPE: angular

includes:
  common: ./.common/taskfiles-app/Taskfile-common.yml
  angular: ./.common/taskfiles-app/Taskfile-angular.yml
  fix: ./.common/taskfiles-app/Taskfile-fix.yml
  lint: ./.common/taskfiles-app/Taskfile-lint.yml
  software: ./.common/taskfiles-app/Taskfile-{{OS}}.yml
