---
stages:
  - update
  - lint
  - test
  - lsif
  - build
  - publish

include:
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/build/android.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/build/electron.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/build/extensions.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/build/ios.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/build/menubar.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/eslint.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/prettier.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/shellcheck.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/stylelint.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lint/yamllint.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/lsif/typescript.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/publish/angular/artifacts.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/publish/docs/typedoc.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/publish/npm/npmjs.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/publish/web/firebase.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/test/jest.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/test/jest-e2e.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/update/project.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
